name: SpeedRunnerVsHunter
main: fr.viazel.speedrunnervshunter.Main
version: 1.0
description: Askip c'est le plugin d'un speedrunner
api-version: 1.19
author: Viazel
commands:
  start:
    description: START !!
  end:
    description: ENDNND
  setspawn:
    description: qiujsdfhioqsfd